version: '3.7'

services:
  eureka-server:
    image: naming-service
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - minha_rede
    restart: always

  frontend:
    image: microservico-frontend
    container_name: microservico-frontend
    ports:
      - "80:80"
    networks:
      - minha_rede
    command: sh -c "java $JAVA_OPTS -jar \Microservico-FrontEnd-Server\target\Microservico-FrontEnd-Server-0.0.1-SNAPSHOT.jar"
    depends_on:
      - eureka-server
    restart: always

  api-gateway:
    image: api-gateway
    container_name: api-gateway
    ports:
      - "8755:8755"
    networks:
      - minha_rede
    command: sh -c "java $JAVA_OPTS -jar \API-Cloud-Gateway\target\API-Cloud-Gateway-0.0.1-SNAPSHOT.jar"
    depends_on:
      - eureka-server
    restart: always

  sessoes-carregamento:
    image: microservico-sessoes-carregamento
    container_name: microservico-sessoes-carregamento
    ports:
      - "8040:8040"
    networks:
      - minha_rede
    command: sh -c "java $JAVA_OPTS -jar \Microservico-Simulacao-Sessoes-Carregamento\target\Microservico-Simulacao-Sessoes-Carregamento-0.0.1-SNAPSHOT.jar"
    depends_on:
      - eureka-server
    restart: always

  utilizadores-veiculos:
    image: microservico-utilizadores-veiculos
    container_name: microservico-utilizadores-veiculos
    ports:
      - "8030:8030"
    networks:
      - minha_rede
    command: sh -c "java $JAVA_OPTS -jar \Microservico-Utilizadores-Veiculos\target\Microservico-Utilizadores-Veiculos-0.0.1-SNAPSHOT.jar"
    depends_on:
      - eureka-server
    restart: always

  ceme-faturacao:
    image: microservico-ceme-faturacao
    container_name: microservico-ceme-faturacao
    ports:
      - "8050:8050"
    networks:
      - minha_rede
    command: sh -c "java $JAVA_OPTS -jar \Microservico-CEME-Faturacao\target\Microservico-CEME-Faturacao-0.0.1-SNAPSHOT.jar"
    depends_on:
      - eureka-server
    restart: always

  opc:
    image: microservico-opc
    container_name: microservico-opc
    ports:
      - "8020:8020"
    networks:
      - minha_rede
    command: sh -c "java $JAVA_OPTS -jar \OPC\target\OPC-0.0.1-SNAPSHOT.jar"
    depends_on:
      - eureka-server
    restart: always

networks:
  minha_rede:
    driver: bridge
